[package]
name = "neolink"
version = "0.1.0"
authors = ["George Hilliard <thirtythreeforty@gmail.com>"]
edition = "2018"

***REMOVED*** See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
