[package]
name = "neolink"
description = "A standards-compliant bridge to Reolink IP cameras"
version = "0.2.0"
authors = ["George Hilliard <thirtythreeforty@gmail.com>"]
edition = "2018"

***REMOVED*** See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cookie-factory = "0.3"
crossbeam = "0.7"
env_logger = "*"
err-derive = "0.2"
glib = "*"
gstreamer = "0.15"
gstreamer-app = "0.15"
gstreamer-rtsp = "0.15"
gstreamer-rtsp-server = "0.15"
lazy_static = "1.4"
log = { version = "0.4" }
indoc = "0.3"
md5 = "0.7"
nom = "5.1"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
socket2 = "0.3"
structopt = "0.3"
toml = "0.5"
yaserde = "0.3.16"
yaserde_derive = "0.3.16"
xml-rs = "0.8"
validator = "0.10"
validator_derive = "0.10"
