name: CI

on: [push]

jobs:
  ubuntu:
    name: neolink-ubuntu
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt update
      - run: sudo apt install -y libgstrtspserver-1.0-dev libgstreamer1.0-dev libgstreamer-plugins-bad1.0-dev libgstreamer-plugins-good1.0-dev
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - uses: actions/upload-artifact@v2
        with:
          name: release
          path: target/release/neolink

  win:
    name: neolink-win2019
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - run: choco install gstreamer
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - uses: actions/upload-artifact@v2
        with:
          name: release
          path: target/release/neolink.exe
